/** List of product categories, subcategories and their translations to FR */
export const products = {
    categories: {
        CLOTHING: {
            tag: 'Vêtements',
            subcategories: {
                BATHROBES: 'Peignoirs',
                COATS: 'Manteaux',
                DRESSES: 'Robes',
                JACKETS: 'Vestes',
                JEANS: 'Jeans',
                OTHER: 'Autre',
                PAJAMAS: 'Pyjamas',
                SHIRTS: 'Chemises',
                SKIRTS: 'Jupes',
                SOCKS: 'Chaussettes',
                SUITS: 'Costumes',
                SWEATERS: 'Pulls',
                SWIMWEAR: 'Maillots de bain',
                T_SHIRTS: 'T-shirts',
                TROUSERS: 'Pantalons',
                UNDERWEAR: 'Sous-vêtements',
            },
        },
        SHOES: {
            tag: 'Chaussures',
            subcategories: {
                BOOTS: 'Bottes',
                DRESS_SHOES: 'Chaussures habillées',
                ESPADRILLES: 'Espadrilles',
                FLIP_FLOPS: 'Tongs',
                HIGH_HEELS: 'Chaussures à talons',
                HIKING_SHOES: 'Chaussures de randonnée',
                LOAFERS: 'Mocassins',
                OTHER: 'Autre',
                SANDALS: 'Sandales',
                SAFETY_SHOES: 'Chaussures de sécurité',
                SNEAKERS: 'Baskets',
                SPORTS: 'Chaussures de sport',
            },
        },
        ACCESSORIES_LUGGAGE: {
            tag: 'Accessoires et bagages',
            subcategories: {
                BACKPACKS: 'Sacs à dos',
                BEANIES: 'Bonnets',
                BELTS: 'Ceintures',
                CAPS: 'Casquettes',
                GLOVES: 'Gants',
                HANDBAGS: 'Sacs à main',
                HATS: 'Chapeaux',
                KEYCHAINS: 'Porte-clés',
                NECK_SCARVES: 'Foulards',
                OTHER: 'Autre',
                SCARVES: 'Écharpes',
                SUNGLASSES: 'Lunettes de soleil',
                SUITCASES: 'Valises',
                TOILETRY_BAGS: 'Trousses de toilette',
                UMBRELLAS: 'Parapluies',
                WALLETS: 'Portefeuilles',
            },
        },
        WATCHES_JEWELLERY: {
            tag: 'Montres et bijoux',
            subcategories: {
                BRACELETS: 'Bracelets',
                BROOCHES: 'Broches',
                COSTUME_JEWELRY: 'Bijoux fantaisie',
                EARRINGS: 'Boucles d’oreilles',
                GEMSTONES: 'Pierres précieuses',
                GOLD_JEWELRY: 'Bijoux en or',
                NECKLACES: 'Colliers',
                PENDANTS: 'Pendentifs',
                PRECIOUS_STONES: 'Pierres précieuses',
                RINGS: 'Bagues',
                OTHER: 'Autre',
                SILVER_JEWELRY: 'Bijoux en argent',
                WATCH_ACCESSORIES: 'Accessoires pour montres',
                WATCHES: 'Montres',
            },
        },
        BABY: {
            tag: 'Bébé',
            subcategories: {
                BABY_ACCESSORIES: 'Accessoires bébé',
                BABY_FOOTWEAR: 'Chaussures bébé',
                BABY_HATS: 'Bonnets bébé',
                BABY_JACKETS: 'Vestes bébé',
                BABY_PAJAMAS: 'Pyjamas bébé',
                BABY_ROMPERS: 'Combinaisons bébé',
                BABY_SHOES: 'Chaussons bébé',
                BIBS: 'Bavoirs',
                BODYSUITS: 'Bodies',
                CHRISTENING_CLOTHES: 'Vêtements de baptême',
                OTHER: 'Autre',
                OVERALLS: 'Salopettes',
                SLEEP_SACKS: 'Gigoteuses',
            },
        },
        GAMES_TOYS: {
            tag: 'Jeux et jouets',
            subcategories: {
                ACTION_FIGURES: 'Figurines',
                BOARD_GAMES: 'Jeux de société',
                CONSTRUCTION_TOYS: 'Jeux de construction',
                CREATIVE_TOYS: 'Jeux créatifs',
                DIY_KITS: 'Kits de bricolage',
                DOLLS: 'Poupées',
                EDUCATIONAL_TOYS: 'Jeux éducatifs',
                ELECTRONIC_GAMES: 'Jeux électroniques',
                OTHER: 'Autre',
                OUTDOOR_TOYS: 'Jeux d’extérieur',
                PUZZLES: 'Puzzles',
                ROLE_PLAYING_GAMES: 'Jeux de rôle',
                STUFFED_ANIMALS: 'Peluches',
                TOY_VEHICLES: 'Véhicules miniatures',
                VIDEO_GAMES: 'Jeux vidéo',
            },
        },
        FURNITURE: {
            tag: 'Meubles',
            subcategories: {
                ARMCHAIRS: 'Fauteuils',
                BEDS: 'Lits',
                CHAIRS: 'Chaises',
                COFFEE_TABLES: 'Tables basses',
                DESKS: 'Bureaux',
                DRESSERS: 'Commodes',
                OTHER: 'Autre',
                SHELVES: 'Étagères',
                SIDEBOARDS: 'Buffets',
                SOFAS: 'Canapés',
                STOOLS: 'Tabourets',
                STORAGE_UNITS: 'Rangements',
                TABLES: 'Tables',
                TV_STANDS: 'Meubles TV',
                WARDROBES: 'Armoires',
            },
        },
        APPLIANCES: {
            tag: 'Appareils électroménagers',
            subcategories: {
                AIR_CONDITIONERS: 'Climatiseurs',
                BLENDERS: 'Mixeurs',
                COFFEE_MAKERS: 'Cafetières',
                DISHWASHERS: 'Lave-vaisselle',
                DRYERS: 'Sèche-linge',
                FANS: 'Ventilateurs',
                FOOD_PROCESSORS: 'Robots de cuisine',
                KETTLES: 'Bouilloires',
                MICROWAVES: 'Micro-ondes',
                OTHER: 'Autre',
                OVENS: 'Fours',
                REFRIGERATORS: 'Réfrigérateurs',
                TOASTERS: 'Grille-pain',
                VACUUM_CLEANERS: 'Aspirateurs',
                WASHING_MACHINES: 'Lave-linge',
                WATER_HEATERS: 'Chauffe-eau',
            },
        },
        DECORATION: {
            tag: 'Décoration',
            subcategories: {
                ARTIFICIAL_PLANTS: 'Plantes artificielles',
                CANDLES: 'Bougies',
                CLOCKS: 'Horloges',
                CUSHIONS: 'Coussins',
                CURTAINS: 'Rideaux',
                DECORATIVE_BASKETS: 'Paniers décoratifs',
                DECORATIVE_OBJECTS: 'Objets décoratifs',
                LAMPS: 'Lampes',
                MIRRORS: 'Miroirs',
                PAINTINGS: 'Tableaux',
                PHOTO_FRAMES: 'Cadres photo',
                RUGS: 'Tapis',
                OTHER: 'Autre',
                VASES: 'Vases',
            },
        },
        ELECTRONICS: {
            tag: 'Électronique',
            subcategories: {
                ACTION_CAMERAS: 'Caméras d’action',
                AUDIO_RECEIVERS: 'Récepteurs audio',
                BLUETOOTH_SPEAKERS: 'Enceintes Bluetooth',
                CAMERAS: 'Appareils photo',
                COMPUTER_COMPONENTS: 'Composants d’ordinateur',
                DESKTOP_COMPUTERS: 'Ordinateurs de bureau',
                DRONES: 'Drones',
                E_READERS: 'Liseuses',
                ELECTRONIC_ACCESSORIES: 'Accessoires électroniques',
                EXTERNAL_STORAGE: 'Stockage externe',
                GAMING_CONSOLES: 'Consoles de jeu',
                GPS_DEVICES: 'Appareils GPS',
                HEADPHONES: 'Casques audio',
                KEYBOARDS: 'Claviers',
                LAPTOPS: 'Ordinateurs portables',
                LOUDSPEAKERS: 'Enceintes',
                MICROPHONES: 'Microphones',
                MOBILE_PHONES: 'Téléphones mobiles',
                MONITORS: 'Écrans',
                NETWORK_EQUIPMENT: 'Équipement réseau',
                OTHER: 'Autre',
                PRINTERS: 'Imprimantes',
                PROJECTORS: 'Projecteurs',
                SMART_HOME_DEVICES: 'Appareils domotiques',
                SMARTWATCHES: 'Montres connectées',
                TABLETS: 'Tablettes',
                TELEVISIONS: 'Télévisions',
            },
        },
        BIKES: {
            tag: 'Vélos',
            subcategories: {
                BIKE_ACCESSORIES: 'Accessoires vélo',
                BIKE_PARTS: 'Pièces détachées vélo',
                BMX_BIKES: 'BMX',
                CITY_BIKES: 'Vélos de ville',
                CYCLING_GEAR: 'Équipements cyclistes',
                ELECTRIC_BIKES: 'Vélos électriques',
                FOLDING_BIKES: 'Vélos pliants',
                HYBRID_BIKES: 'Vélos hybrides',
                KIDS_BIKES: 'Vélos pour enfants',
                MOUNTAIN_BIKES: 'Vélos de montagne',
                MOUNTAIN_BIKE_ACCESSORIES: 'Accessoires VTT',
                OTHER: 'Autre',
                ROAD_BIKES: 'Vélos de route',
            },
        },
        BOOKS: {
            tag: 'Livres',
            subcategories: {
                ART_BOOKS: 'Livres d’art',
                AUDIOBOOKS: 'Livres audio',
                BIOGRAPHIES: 'Biographies',
                CHILDRENS_BOOKS: 'Livres jeunesse',
                COMIC_BOOKS: 'Bandes dessinées',
                COOKBOOKS: 'Livres de cuisine',
                DICTIONARIES: 'Dictionnaires',
                EBOOKS: 'Livres numériques',
                ESSAYS: 'Essais',
                NOVELS: 'Romans',
                OTHER: 'Autre',
                POETRY: 'Poésie',
                PRACTICAL_GUIDES: 'Guides pratiques',
                TEXTBOOKS: 'Manuels scolaires',
                TRAVEL_BOOKS: 'Livres de voyage',
            },
        },
        SPORT: {
            tag: 'Sport',
            subcategories: {
                BALLS: 'Ballons',
                EXERCISE_BIKES: 'Vélos d’appartement',
                FITNESS_EQUIPMENT: 'Équipement de fitness',
                FOOTBALL_GEAR: 'Articles de football',
                OTHER: 'Autre',
                RACKETS: 'Raquettes',
                SPORTS_BAGS: 'Sacs de sport',
                SPORTS_SHOES: 'Chaussures de sport',
                SPORTSWEAR: 'Vêtements de sport',
                SWIMMING_GEAR: 'Articles de natation',
                TENNIS_GEAR: 'Articles de tennis',
                TREADMILLS: 'Tapis de course',
                WEIGHTLIFTING_EQUIPMENT: 'Équipement de musculation',
                YOGA_EQUIPMENT: 'Équipements pour le yoga',
            },
        },
        BEAUTY: {
            tag: 'Beauté',
            subcategories: {
                BEAUTY_ACCESSORIES: 'Accessoires de beauté',
                BEAUTY_DEVICES: 'Appareils de soin',
                HAIR_PRODUCTS: 'Produits pour cheveux',
                NAIL_CARE: 'Soins des ongles',
                OTHER: 'Autre',
            },
        },
        PET_SUPPLIES: {
            tag: 'Fournitures pour animaux',
            subcategories: {
                AQUARIUMS: 'Aquariums',
                CAGES: 'Cages',
                COLLARS_AND_LEASHES: 'Colliers et laisses',
                GROOMING_ACCESSORIES: 'Accessoires de toilettage',
                LITTER: 'Litières',
                LITTER_BOXES: 'Bacs à litière',
                OTHER: 'Autre',
                PET_CLOTHING: 'Vêtements pour animaux',
                PET_FOOD: 'Nourriture pour animaux',
                PET_TOYS: 'Jouets pour animaux',
                SCRATCHING_POSTS: 'Griffoirs',
            },
        },
        GARDENING: {
            tag: 'Jardinage',
            subcategories: {
                BARBECUES: 'Barbecues',
                GARDEN_FURNITURE: 'Mobilier de jardin',
                GARDENING_TOOLS: 'Outils de jardinage',
                HAMMOCKS: 'Hamacs',
                IRRIGATION_SYSTEMS: 'Systèmes d’irrigation',
                LAWN_MOWERS: 'Tondeuses',
                OTHER: 'Autre',
                OUTDOOR_LIGHTING: 'Éclairages extérieurs',
                PLANTS_AND_FLOWERS: 'Plantes et fleurs',
                SEEDS: 'Graines et semences',
                WATERING_CANS: 'Arrosoirs',
            },
        },
        OTHER: {
            tag: 'Autre',
            subcategories: {
                CAMPING_GEAR: 'Matériel de camping',
                COLLECTIBLES: 'Articles de collection',
                GARDENING_SUPPLIES: 'Matériel de jardinage',
                MEDICAL_EQUIPMENT: 'Équipement médical',
                MISCELLANEOUS: 'Divers',
                MUSICAL_INSTRUMENTS: 'Instruments de musique',
                OFFICE_SUPPLIES: 'Fournitures de bureau',
                OTHER: 'Autre',
                OUTDOOR_GAMES: 'Jeux de plein air',
                PET_SUPPLIES: 'Articles pour animaux',
                RELIGIOUS_ITEMS: 'Articles religieux',
                SPORTS_EQUIPMENT: 'Équipement de sport',
                TOOLS: 'Outils',
            },
        },
    },
}

/** List of product category keys */
export const categoriesList = Object.entries(products.categories)
    .sort(([, a], [, b]) => a.tag.localeCompare(b.tag))
    .map(([key]) => key) as (keyof typeof products.categories)[]

/** List of all product subCategory keys */
export const subcategoriesList = Object.values(products.categories).flatMap(
    (category) =>
        Object.keys(category.subcategories).map((key) =>
            key.replaceAll('_', ' '),
        ),
)

/** List of product subCategory keys */
export const subCategoriesList = Object.keys(
    products.categories,
) as (keyof typeof products.categories)[]

/** Object containing translations for product states */
export const productStates = {
    NEW: 'Neuf',
    LIKE_NEW: 'Comme neuf',
    VERY_GOOD_CONDITION: 'Très bonne condition',
    GOOD_CONDITION: 'Bonne condition',
    FAIR_CONDITION: 'Condition moyenne',
    TO_REPAIR: 'À réparer',
}

export const productStatus = {
    AVAILABLE: 'Disponible',
    UNAVAILABLE: 'Indisponible',
    RESERVED: 'Réservé',
}

export const deliveryTypes = {
    PICKUP: 'En main propre',
    SHIPPING: 'À l’envoi',
    BOTH: 'En main propre ou à l’envoi',
}

export const sizeOptions = [
    { label: 'Vêtements', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
    {
        label: 'Pantalons',
        options: [
            '32',
            '34',
            '36',
            '38',
            '40',
            '42',
            '44',
            '48',
            '50',
            '52',
            '54',
            '56',
            '58',
        ],
    },
    {
        label: 'Chaussures',
        options: [
            '35',
            '36',
            '37',
            '38',
            '39',
            '40',
            '41',
            '42',
            '43',
            '44',
            '45',
            '46',
        ],
    },
    {
        label: 'Soutiens-gorge',
        options: [
            '70A',
            '70B',
            '70C',
            '70D',
            '75A',
            '75B',
            '75C',
            '75D',
            '80A',
            '80B',
            '80C',
            '80D',
            '85A',
            '85B',
            '85C',
            '85D',
        ],
    },
    {
        label: 'Costumes',
        options: ['44', '46', '48', '50', '52', '54', '56', '58'],
    },
]
