import { z } from 'zod'

export const categories = {
    CLOTHING: [
        'T_SHIRTS',
        'SHIRTS',
        'PANTS',
        'JACKETS',
        'SWEATERS',
        'JEANS',
        'DRESSES',
        'SKIRTS',
        'SUITS',
        'UNDERWEAR',
        'SWIMWEAR',
        'COATS',
        'SOCKS',
        'BATHROBES',
        'PAJAMAS',
    ],
    SHOES: [
        'SPORTS_SHOES',
        'DRESS_SHOES',
        'BOOTS',
        'SANDALS',
        'HIKING_SHOES',
        'SNEAKERS',
        'LOAFERS',
        'HIGH_HEELS',
        'ESPADRILLES',
        'SAFETY_SHOES',
        'FLIP_FLOPS',
    ],
    ACCESSORIES_LUGGAGE: [
        'HANDBAGS',
        'BACKPACKS',
        'SUITCASES',
        'WALLETS',
        'BELTS',
        'SUNGLASSES',
        'SCARVES',
        'HATS',
        'GLOVES',
        'UMBRELLAS',
        'KEYCHAINS',
        'TOILETRY_BAGS',
        'CAPS',
        'BEANIES',
        'NECK_SCARVES',
    ],
    WATCHES_JEWELRY: [
        'WATCHES',
        'BRACELETS',
        'NECKLACES',
        'EARRINGS',
        'RINGS',
        'BROOCHES',
        'COSTUME_JEWELRY',
        'GOLD_JEWELRY',
        'SILVER_JEWELRY',
        'PRECIOUS_STONES',
        'WATCH_ACCESSORIES',
        'PENDANTS',
    ],
    BABY_CLOTHING: [
        'BODYSUITS',
        'BABY_PAJAMAS',
        'OVERALLS',
        'SLEEP_SACKS',
        'BABY_HATS',
        'CHRISTENING_CLOTHES',
        'BABY_SHOES',
        'BABY_ROMPERS',
        'BABY_JACKETS',
        'BABY_FOOTWEAR',
        'BABY_ACCESSORIES',
        'BIBS',
    ],
    GAMES_TOYS: [
        'BOARD_GAMES',
        'PUZZLES',
        'STUFFED_ANIMALS',
        'CONSTRUCTION_TOYS',
        'ACTION_FIGURES',
        'DOLLS',
        'TOY_VEHICLES',
        'EDUCATIONAL_TOYS',
        'OUTDOOR_TOYS',
        'ELECTRONIC_GAMES',
        'ROLE_PLAYING_GAMES',
        'CREATIVE_TOYS',
        'VIDEO_GAMES',
        'DIY_KITS',
    ],
    FURNITURE: [
        'SOFAS',
        'TABLES',
        'CHAIRS',
        'DESKS',
        'BEDS',
        'WARDROBES',
        'DRESSERS',
        'STORAGE_UNITS',
        'SIDEBOARDS',
        'STOOLS',
        'SHELVES',
        'ARMCHAIRS',
        'TV_STANDS',
    ],
    APPLIANCES: [
        'REFRIGERATORS',
        'WASHING_MACHINES',
        'DRYERS',
        'DISHWASHERS',
        'OVENS',
        'MICROWAVES',
        'VACUUM_CLEANERS',
        'BLENDERS',
        'FOOD_PROCESSORS',
        'COFFEE_MAKERS',
        'TOASTERS',
        'KETTLES',
        'FANS',
        'AIR_CONDITIONERS',
        'WATER_HEATERS',
    ],
    DECORATION: [
        'PAINTINGS',
        'LAMPS',
        'CUSHIONS',
        'CURTAINS',
        'RUGS',
        'VASES',
        'PHOTO_FRAMES',
        'CANDLES',
        'MIRRORS',
        'ARTIFICIAL_PLANTS',
        'CLOCKS',
        'DECORATIVE_OBJECTS',
        'DECORATIVE_BASKETS',
    ],
    ELECTRONICS: [
        'MOBILE_PHONES',
        'LAPTOPS',
        'TABLETS',
        'CAMERAS',
        'HEADPHONES',
        'BLUETOOTH_SPEAKERS',
        'TELEVISIONS',
        'GAMING_CONSOLES',
        'SMARTWATCHES',
        'ELECTRONIC_ACCESSORIES',
        'DRONES',
        'ACTION_CAMERAS',
        'PRINTERS',
        'PROJECTORS',
    ],
    BICYCLES: [
        'ROAD_BIKES',
        'MOUNTAIN_BIKES',
        'ELECTRIC_BIKES',
        'FOLDING_BIKES',
        'KIDS_BIKES',
        'CITY_BIKES',
        'HYBRID_BIKES',
        'BMX_BIKES',
        'MOUNTAIN_BIKE_ACCESSORIES',
        'BIKE_ACCESSORIES',
        'BIKE_PARTS',
        'CYCLING_GEAR',
    ],
    BOOKS: [
        'NOVELS',
        'COMIC_BOOKS',
        'ESSAYS',
        'CHILDRENS_BOOKS',
        'COOKBOOKS',
        'TRAVEL_BOOKS',
        'BIOGRAPHIES',
        'ART_BOOKS',
        'PRACTICAL_GUIDES',
        'TEXTBOOKS',
        'AUDIOBOOKS',
        'EBOOKS',
        'DICTIONARIES',
        'POETRY',
    ],
    SPORT: [
        'FITNESS_EQUIPMENT',
        'SPORTSWEAR',
        'SPORTS_SHOES',
        'SPORTS_BAGS',
        'FOOTBALL_GEAR',
        'TENNIS_GEAR',
        'SWIMMING_GEAR',
        'WEIGHTLIFTING_EQUIPMENT',
        'RACKETS',
        'EXERCISE_BIKES',
        'TREADMILLS',
        'YOGA_EQUIPMENT',
        'BALLS',
    ],
    BEAUTY: [
        'HAIR_PRODUCTS',
        'NAIL_CARE',
        'BEAUTY_ACCESSORIES',
        'BEAUTY_DEVICES',
    ],
    PET_SUPPLIES: [
        'PET_FOOD',
        'PET_TOYS',
        'LITTER',
        'CAGES',
        'COLLARS_AND_LEASHES',
        'PET_CLOTHING',
        'GROOMING_ACCESSORIES',
        'AQUARIUMS',
        'LITTER_BOXES',
        'SCRATCHING_POSTS',
    ],
    GARDENING: [
        'GARDENING_TOOLS',
        'PLANTS_AND_FLOWERS',
        'GARDEN_FURNITURE',
        'BARBECUES',
        'LAWN_MOWERS',
        'SEEDS',
        'WATERING_CANS',
        'OUTDOOR_LIGHTING',
        'HAMMOCKS',
        'IRRIGATION_SYSTEMS',
    ],
    OTHER: [
        'COLLECTIBLES',
        'MUSICAL_INSTRUMENTS',
        'SPORTS_EQUIPMENT',
        'GARDENING_SUPPLIES',
        'TOOLS',
        'OFFICE_SUPPLIES',
        'BEAUTY_PRODUCTS',
        'PET_SUPPLIES',
        'MEDICAL_EQUIPMENT',
        'CAMPING_GEAR',
        'RELIGIOUS_ITEMS',
        'MISCELLANEOUS',
        'OUTDOOR_GAMES',
    ],
}
/**
 * @description Schema for category enum
 * @exports CategoryEnumSchema
 */
export const CategoryEnumSchema = z.enum(
    Object.keys(categories) as [keyof typeof categories],
)

/**
 * @description Schema for subcategory enum
 * @exports SubcategoryEnumSchema
 */
export const SubcategoryEnumSchema = z.enum(
    Object.values(categories).flat() as [string],
)
