import { z } from 'zod'

export const categories = {
    CLOTHING: [
        'T-shirts',
        'Chemises',
        'Pantalons',
        'Vestes',
        'Pulls',
        'Jeans',
        'Robes',
        'Jupes',
        'Costumes',
        'Sous-vêtements',
        'Maillots de bain',
        'Manteaux',
    ],
    SHOES: [
        'Chaussures de sport',
        'Chaussures habillées',
        'Bottes',
        'Sandales',
        'Chaussures de randonnée',
        'Baskets',
        'Mocassins',
        'Chaussures à talons',
        'Espadrilles',
    ],
    ACCESSORIES_LUGGAGE: [
        'Sacs à main',
        'Sacs à dos',
        'Valises',
        'Portefeuilles',
        'Ceintures',
        'Lunettes de soleil',
        'Écharpes',
        'Chapeaux',
        'Gants',
        'Parapluies',
        'Porte-clés',
        'Trousses de toilette',
    ],
    WATCHES_JEWELRY: [
        'Montres',
        'Bracelets',
        'Colliers',
        'Boucles d’oreilles',
        'Bagues',
        'Broches',
        'Bijoux fantaisie',
        'Bijoux en or',
        'Bijoux en argent',
        'Pierres précieuses',
        'Accessoires pour montres',
    ],
    BABY_CLOTHING: [
        'Bodies',
        'Pyjamas',
        'Salopettes',
        'Gigoteuses',
        'Bonnets',
        'Vêtements de baptême',
        'Chaussons',
        'Combinaisons',
        'Vestes bébé',
        'Chaussures bébé',
        'Accessoires bébé',
    ],
    GAMES_TOYS: [
        'Jeux de société',
        'Puzzles',
        'Peluches',
        'Jeux de construction',
        'Figurines',
        'Poupées',
        'Véhicules miniatures',
        'Jeux éducatifs',
        'Jeux d’extérieur',
        'Jeux électroniques',
        'Jeux de rôle',
        'Jeux créatifs',
    ],
    FURNITURE: [
        'Canapés',
        'Tables',
        'Chaises',
        'Bureaux',
        'Lits',
        'Armoires',
        'Commodes',
        'Rangements',
        'Buffets',
        'Tabourets',
        'Étagères',
        'Fauteuils',
    ],
    APPLIANCES: [
        'Réfrigérateurs',
        'Lave-linge',
        'Sèche-linge',
        'Lave-vaisselle',
        'Fours',
        'Micro-ondes',
        'Aspirateurs',
        'Mixeurs',
        'Robots de cuisine',
        'Cafetières',
        'Grille-pain',
        'Bouilloires',
    ],
    DECORATION: [
        'Tableaux',
        'Lampes',
        'Coussins',
        'Rideaux',
        'Tapis',
        'Vases',
        'Cadres photo',
        'Bougies',
        'Miroirs',
        'Plantes artificielles',
        'Horloges',
        'Objets décoratifs',
    ],
    ELECTRONICS: [
        'Téléphones mobiles',
        'Ordinateurs portables',
        'Tablettes',
        'Appareils photo',
        'Casques audio',
        'Enceintes Bluetooth',
        'Télévisions',
        'Consoles de jeu',
        'Smartwatches',
        'Accessoires électroniques',
        'Drones',
        'Caméras d’action',
    ],
    BICYCLES: [
        'Vélos de route',
        'Vélos de montagne',
        'Vélos électriques',
        'Vélos pliants',
        'Vélos pour enfants',
        'Vélos de ville',
        'Vélos hybrides',
        'BMX',
        'VTT',
        'Accessoires vélo',
        'Pièces détachées',
        'Équipements cyclistes',
    ],
    BOOKS: [
        'Romans',
        'Bandes dessinées',
        'Essais',
        'Livres jeunesse',
        'Livres de cuisine',
        'Livres de voyage',
        'Biographies',
        'Livres d’art',
        'Guides pratiques',
        'Manuels scolaires',
        'Livres audio',
        'Livres numériques',
    ],
    OTHER: [
        'Articles de collection',
        'Instruments de musique',
        'Équipement de sport',
        'Matériel de jardinage',
        'Outils',
        'Fournitures de bureau',
        'Produits de beauté',
        'Articles pour animaux',
        'Équipement médical',
        'Matériel de camping',
        'Articles religieux',
        'Divers',
    ],
}

/**
 * @description Schema for category enum
 * @exports CategoryEnumSchema
 */
export const CategoryEnumSchema = z.enum(
    Object.keys(categories) as [keyof typeof categories],
)

/**
 * @description Schema for subcategory enum
 * @exports SubcategoryEnumSchema
 */
export const SubcategoryEnumSchema = z.enum(
    Object.values(categories).flat() as [string],
)
